export default [
  {
    id: "1",
    title: "Sami et Julie à la plage",
    object: "Hello",
    message: "How are you?",
    date: "Feb 17th 2021",
  },
  {
    id: "2",
    title: "Le petit Chaperon rouge",
    object: "Hi!",
    message: "I want to get that book please",
    date: "Feb 17th 2021",
  },
  {
    id: "3",
    title: "Le grand imagier de la nature",
    object: "https:/",
    message: "Munis de leur seau ",
    date: "Feb 17th 2021",
  },
  {
    id: "4",
    title: "Ludanimo",
    object: "https:/",
    message: "Munis de leur seau ",
    date: "Feb 17th 2021",
  },
  {
    id: "5",
    title: "Mon amour",
    object: "https:/",
    message: "Munis de leur seau ",
    date: "Feb 17th 2021",
  },
  {
    id: "6",
    title: "Le Verger, jeu de cartes",
    object: "https:/",
    message: "Munis de leur seau ",
    date: "Feb 17th 2021",
  },
  {
    id: "7",
    title: "La Fontaine raconte aux enfants",
    object: "https:/",
    message: "Munis de leur seau ",
    date: "Feb 17th 2021",
  },
  {
    id: "8",
    title: "La tour Eiffel se balade à Paris",
    object: "https:/",
    message: "Munis de leur seau ",
    date: "Feb 17th 2021",
  },
];
